package edu.colostate.cs.cs414.warewolves.chad.client.gui.swing.panels;

import edu.colostate.cs.cs414.warewolves.chad.client.gui.ChadGameDriver;
import edu.colostate.cs.cs414.warewolves.chad.client.presenter.controller.messages.UnregisterMessage;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 * Panel for creating an unregistering account. It asks the user to verify their
 * email address, nickname, and password.
 */
public class UnregisterAccountPanel extends JPanel {

  /**
   * Main panel for the class
   */
  private JPanel mainPanel;
  /**
   * Text field for users nickname
   */
  private JTextField nicknameField;
  /**
   * Text field for users email
   */
  private JTextField emailField;
  /**
   * Text field for users password
   */
  private JPasswordField passwordField;
  /**
   * Button to unregister account
   */
  private JButton unregisterAccount;
  /**
   * Button to go back to main menu
   */
  private JButton cancelRegister;


  /**
   * Creates the GUI elements and sets the panels controller for ActionListeners
   *
   * @param controller the controller of the panel
   */
  public UnregisterAccountPanel(ChadGameDriver controller) {
    // Setup cancel button
    cancelRegister.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        try {
          // send message to controller with invalid UnregisterMessage
          controller.handleViewMessage(new UnregisterMessage(null, "", null));
        } catch (NoSuchAlgorithmException e1) {
          System.err.println("The computer does not have SHA1 algorithm");
        }
      }
    });

    // Setup cancel button
    unregisterAccount.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        // Get user info
        String email = emailField.getText();
        String nickname = nicknameField.getText();
        String password = new String(passwordField.getPassword());
        // All fields must have data
        if (email.isEmpty() || password.isEmpty() || nickname.isEmpty()) {
          JOptionPane.showMessageDialog(mainPanel,
              "You must enter values in the Email, Nickname, and Password fields");
          return;
        }
        try {
          // Send  unregistration request
          passwordField.setText(""); // clear password
          UnregisterMessage message = new UnregisterMessage(email, password, nickname);
          controller.handleViewMessage(message);
        } catch (NoSuchAlgorithmException e1) {
          System.err.println("The computer does not have SHA1 algorithm");
        }

      }
    });
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) {
      return null;
    }
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    return new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
        size >= 0 ? size : currentFont.getSize());
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(0, 0));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridBagLayout());
    mainPanel.add(panel1, BorderLayout.CENTER);
    final JPanel spacer1 = new JPanel();
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel1.add(spacer1, gbc);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new BorderLayout(0, 0));
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    panel1.add(panel2, gbc);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridBagLayout());
    panel2.add(panel3, BorderLayout.CENTER);
    final JLabel label1 = new JLabel();
    label1.setText("Account Nickname");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    panel3.add(label1, gbc);
    nicknameField = new JTextField();
    nicknameField.setColumns(30);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel3.add(nicknameField, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel3.add(spacer2, gbc);
    final JLabel label2 = new JLabel();
    label2.setText("Account Email ");
    label2.putClientProperty("html.disable", Boolean.FALSE);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    panel3.add(label2, gbc);
    emailField = new JTextField();
    emailField.setColumns(30);
    emailField.setVerifyInputWhenFocusTarget(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    panel3.add(emailField, gbc);
    final JLabel label3 = new JLabel();
    label3.setText("Password");
    label3.putClientProperty("html.disable", Boolean.FALSE);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    panel3.add(label3, gbc);
    passwordField = new JPasswordField();
    passwordField.setColumns(30);
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 3;
    panel3.add(passwordField, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel3.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel3.add(spacer4, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel3.add(spacer5, gbc);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.VERTICAL;
    panel3.add(spacer6, gbc);
    final JPanel panel4 = new JPanel();
    panel4.setLayout(new BorderLayout(0, 0));
    panel2.add(panel4, BorderLayout.NORTH);
    final JPanel panel5 = new JPanel();
    panel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel4.add(panel5, BorderLayout.NORTH);
    final JLabel label4 = new JLabel();
    Font label4Font = this.$$$getFont$$$(null, -1, -1, label4.getFont());
    if (label4Font != null) {
      label4.setFont(label4Font);
    }
    label4.setText("Please enter your account infromation to unregister");
    panel5.add(label4);
    final JPanel panel6 = new JPanel();
    panel6.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel4.add(panel6, BorderLayout.CENTER);
    final JLabel label5 = new JLabel();
    Font label5Font = this.$$$getFont$$$(null, Font.BOLD, 14, label5.getFont());
    if (label5Font != null) {
      label5.setFont(label5Font);
    }
    label5.setForeground(new Color(-4509164));
    label5.setText("There is no way to undo this action");
    panel6.add(label5);
    final JPanel panel7 = new JPanel();
    panel7.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    panel1.add(panel7, gbc);
    unregisterAccount = new JButton();
    unregisterAccount.setActionCommand("Unregister Account");
    unregisterAccount.setLabel("Unregister Account");
    unregisterAccount.setText("Unregister Account");
    panel7.add(unregisterAccount);
    cancelRegister = new JButton();
    cancelRegister.setActionCommand("Login Screen");
    cancelRegister.setText("Cancel");
    panel7.add(cancelRegister);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
